server:
  port: 8303
spring:
  application:
    name: borrow-service
  cloud:
    nacos:
      config:
        enabled: true
      discovery:
        server-addr: localhost:8801
        username: nacos
        password: java711cSSS#
        namespace: e4bf9822-1052-4c7b-a567-10f7fff2a1bd
        ephemeral: true
        cluster-name: sz
    loadbalancer:
      nacos:
        enabled: true

